// Code generated by ent, DO NOT EDIT.

package upstreamconnection

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamconnection type in the database.
	Label = "upstream_connection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldEncryptedCredential holds the string denoting the encrypted_credential field in the database.
	FieldEncryptedCredential = "encrypted_credential"
	// FieldCredentialVersion holds the string denoting the credential_version field in the database.
	FieldCredentialVersion = "credential_version"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEvidenceRef holds the string denoting the evidence_ref field in the database.
	FieldEvidenceRef = "evidence_ref"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeConnectionProbes holds the string denoting the connection_probes edge name in mutations.
	EdgeConnectionProbes = "connection_probes"
	// EdgeProxy holds the string denoting the proxy edge name in mutations.
	EdgeProxy = "proxy"
	// Table holds the table name of the upstreamconnection in the database.
	Table = "upstream_connections"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "connection_id"
	// ConnectionProbesTable is the table that holds the connection_probes relation/edge.
	ConnectionProbesTable = "account_endpoint_probes"
	// ConnectionProbesInverseTable is the table name for the AccountEndpointProbe entity.
	// It exists in this package in order to avoid circular dependency with the "accountendpointprobe" package.
	ConnectionProbesInverseTable = "account_endpoint_probes"
	// ConnectionProbesColumn is the table column denoting the connection_probes relation/edge.
	ConnectionProbesColumn = "connection_id"
	// ProxyTable is the table that holds the proxy relation/edge.
	ProxyTable = "upstream_connections"
	// ProxyInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxyInverseTable = "proxies"
	// ProxyColumn is the table column denoting the proxy relation/edge.
	ProxyColumn = "proxy_id"
)

// Columns holds all SQL columns for upstreamconnection fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldKind,
	FieldProvider,
	FieldBaseURL,
	FieldEncryptedCredential,
	FieldCredentialVersion,
	FieldProxyID,
	FieldStatus,
	FieldEvidenceRef,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// EncryptedCredentialValidator is a validator for the "encrypted_credential" field. It is called by the builders before save.
	EncryptedCredentialValidator func(string) error
	// DefaultCredentialVersion holds the default value on creation for the "credential_version" field.
	DefaultCredentialVersion int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the UpstreamConnection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByEncryptedCredential orders the results by the encrypted_credential field.
func ByEncryptedCredential(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedCredential, opts...).ToFunc()
}

// ByCredentialVersion orders the results by the credential_version field.
func ByCredentialVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialVersion, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEvidenceRef orders the results by the evidence_ref field.
func ByEvidenceRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvidenceRef, opts...).ToFunc()
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByConnectionProbesCount orders the results by connection_probes count.
func ByConnectionProbesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConnectionProbesStep(), opts...)
	}
}

// ByConnectionProbes orders the results by connection_probes terms.
func ByConnectionProbes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectionProbesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProxyField orders the results by proxy field.
func ByProxyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
	)
}
func newConnectionProbesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectionProbesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ConnectionProbesTable, ConnectionProbesColumn),
	)
}
func newProxyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
	)
}
