// Code generated by ent, DO NOT EDIT.

package upstreamconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldDeletedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldKind, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldProvider, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldBaseURL, v))
}

// EncryptedCredential applies equality check predicate on the "encrypted_credential" field. It's identical to EncryptedCredentialEQ.
func EncryptedCredential(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldEncryptedCredential, v))
}

// CredentialVersion applies equality check predicate on the "credential_version" field. It's identical to CredentialVersionEQ.
func CredentialVersion(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCredentialVersion, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldProxyID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldStatus, v))
}

// EvidenceRef applies equality check predicate on the "evidence_ref" field. It's identical to EvidenceRefEQ.
func EvidenceRef(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldEvidenceRef, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldDeletedAt))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldKind, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldProvider, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldBaseURL, v))
}

// EncryptedCredentialEQ applies the EQ predicate on the "encrypted_credential" field.
func EncryptedCredentialEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldEncryptedCredential, v))
}

// EncryptedCredentialNEQ applies the NEQ predicate on the "encrypted_credential" field.
func EncryptedCredentialNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldEncryptedCredential, v))
}

// EncryptedCredentialIn applies the In predicate on the "encrypted_credential" field.
func EncryptedCredentialIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldEncryptedCredential, vs...))
}

// EncryptedCredentialNotIn applies the NotIn predicate on the "encrypted_credential" field.
func EncryptedCredentialNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldEncryptedCredential, vs...))
}

// EncryptedCredentialGT applies the GT predicate on the "encrypted_credential" field.
func EncryptedCredentialGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldEncryptedCredential, v))
}

// EncryptedCredentialGTE applies the GTE predicate on the "encrypted_credential" field.
func EncryptedCredentialGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldEncryptedCredential, v))
}

// EncryptedCredentialLT applies the LT predicate on the "encrypted_credential" field.
func EncryptedCredentialLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldEncryptedCredential, v))
}

// EncryptedCredentialLTE applies the LTE predicate on the "encrypted_credential" field.
func EncryptedCredentialLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldEncryptedCredential, v))
}

// EncryptedCredentialContains applies the Contains predicate on the "encrypted_credential" field.
func EncryptedCredentialContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldEncryptedCredential, v))
}

// EncryptedCredentialHasPrefix applies the HasPrefix predicate on the "encrypted_credential" field.
func EncryptedCredentialHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldEncryptedCredential, v))
}

// EncryptedCredentialHasSuffix applies the HasSuffix predicate on the "encrypted_credential" field.
func EncryptedCredentialHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldEncryptedCredential, v))
}

// EncryptedCredentialEqualFold applies the EqualFold predicate on the "encrypted_credential" field.
func EncryptedCredentialEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldEncryptedCredential, v))
}

// EncryptedCredentialContainsFold applies the ContainsFold predicate on the "encrypted_credential" field.
func EncryptedCredentialContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldEncryptedCredential, v))
}

// CredentialVersionEQ applies the EQ predicate on the "credential_version" field.
func CredentialVersionEQ(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCredentialVersion, v))
}

// CredentialVersionNEQ applies the NEQ predicate on the "credential_version" field.
func CredentialVersionNEQ(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldCredentialVersion, v))
}

// CredentialVersionIn applies the In predicate on the "credential_version" field.
func CredentialVersionIn(vs ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldCredentialVersion, vs...))
}

// CredentialVersionNotIn applies the NotIn predicate on the "credential_version" field.
func CredentialVersionNotIn(vs ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldCredentialVersion, vs...))
}

// CredentialVersionGT applies the GT predicate on the "credential_version" field.
func CredentialVersionGT(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldCredentialVersion, v))
}

// CredentialVersionGTE applies the GTE predicate on the "credential_version" field.
func CredentialVersionGTE(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldCredentialVersion, v))
}

// CredentialVersionLT applies the LT predicate on the "credential_version" field.
func CredentialVersionLT(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldCredentialVersion, v))
}

// CredentialVersionLTE applies the LTE predicate on the "credential_version" field.
func CredentialVersionLTE(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldCredentialVersion, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldProxyID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldStatus, v))
}

// EvidenceRefEQ applies the EQ predicate on the "evidence_ref" field.
func EvidenceRefEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldEvidenceRef, v))
}

// EvidenceRefNEQ applies the NEQ predicate on the "evidence_ref" field.
func EvidenceRefNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldEvidenceRef, v))
}

// EvidenceRefIn applies the In predicate on the "evidence_ref" field.
func EvidenceRefIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldEvidenceRef, vs...))
}

// EvidenceRefNotIn applies the NotIn predicate on the "evidence_ref" field.
func EvidenceRefNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldEvidenceRef, vs...))
}

// EvidenceRefGT applies the GT predicate on the "evidence_ref" field.
func EvidenceRefGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldEvidenceRef, v))
}

// EvidenceRefGTE applies the GTE predicate on the "evidence_ref" field.
func EvidenceRefGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldEvidenceRef, v))
}

// EvidenceRefLT applies the LT predicate on the "evidence_ref" field.
func EvidenceRefLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldEvidenceRef, v))
}

// EvidenceRefLTE applies the LTE predicate on the "evidence_ref" field.
func EvidenceRefLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldEvidenceRef, v))
}

// EvidenceRefContains applies the Contains predicate on the "evidence_ref" field.
func EvidenceRefContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldEvidenceRef, v))
}

// EvidenceRefHasPrefix applies the HasPrefix predicate on the "evidence_ref" field.
func EvidenceRefHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldEvidenceRef, v))
}

// EvidenceRefHasSuffix applies the HasSuffix predicate on the "evidence_ref" field.
func EvidenceRefHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldEvidenceRef, v))
}

// EvidenceRefIsNil applies the IsNil predicate on the "evidence_ref" field.
func EvidenceRefIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldEvidenceRef))
}

// EvidenceRefNotNil applies the NotNil predicate on the "evidence_ref" field.
func EvidenceRefNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldEvidenceRef))
}

// EvidenceRefEqualFold applies the EqualFold predicate on the "evidence_ref" field.
func EvidenceRefEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldEvidenceRef, v))
}

// EvidenceRefContainsFold applies the ContainsFold predicate on the "evidence_ref" field.
func EvidenceRefContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldEvidenceRef, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConnectionProbes applies the HasEdge predicate on the "connection_probes" edge.
func HasConnectionProbes() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ConnectionProbesTable, ConnectionProbesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionProbesWith applies the HasEdge predicate on the "connection_probes" edge with a given conditions (other predicates).
func HasConnectionProbesWith(preds ...predicate.AccountEndpointProbe) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := newConnectionProbesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamConnection) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamConnection) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamConnection) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.NotPredicates(p))
}
