// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountendpointprobe"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// AccountEndpointProbeUpdate is the builder for updating AccountEndpointProbe entities.
type AccountEndpointProbeUpdate struct {
	config
	hooks    []Hook
	mutation *AccountEndpointProbeMutation
}

// Where appends a list predicates to the AccountEndpointProbeUpdate builder.
func (_u *AccountEndpointProbeUpdate) Where(ps ...predicate.AccountEndpointProbe) *AccountEndpointProbeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountEndpointProbeUpdate) SetAccountID(v int64) *AccountEndpointProbeUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableAccountID(v *int64) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *AccountEndpointProbeUpdate) SetConnectionID(v int64) *AccountEndpointProbeUpdate {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableConnectionID(v *int64) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountEndpointProbeUpdate) SetProvider(v string) *AccountEndpointProbeUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableProvider(v *string) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *AccountEndpointProbeUpdate) SetProtocol(v string) *AccountEndpointProbeUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableProtocol(v *string) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetNormalizedEndpointPath sets the "normalized_endpoint_path" field.
func (_u *AccountEndpointProbeUpdate) SetNormalizedEndpointPath(v string) *AccountEndpointProbeUpdate {
	_u.mutation.SetNormalizedEndpointPath(v)
	return _u
}

// SetNillableNormalizedEndpointPath sets the "normalized_endpoint_path" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableNormalizedEndpointPath(v *string) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetNormalizedEndpointPath(*v)
	}
	return _u
}

// SetCredentialVersion sets the "credential_version" field.
func (_u *AccountEndpointProbeUpdate) SetCredentialVersion(v int64) *AccountEndpointProbeUpdate {
	_u.mutation.ResetCredentialVersion()
	_u.mutation.SetCredentialVersion(v)
	return _u
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableCredentialVersion(v *int64) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetCredentialVersion(*v)
	}
	return _u
}

// AddCredentialVersion adds value to the "credential_version" field.
func (_u *AccountEndpointProbeUpdate) AddCredentialVersion(v int64) *AccountEndpointProbeUpdate {
	_u.mutation.AddCredentialVersion(v)
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *AccountEndpointProbeUpdate) SetConfigVersion(v int64) *AccountEndpointProbeUpdate {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableConfigVersion(v *int64) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *AccountEndpointProbeUpdate) AddConfigVersion(v int64) *AccountEndpointProbeUpdate {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountEndpointProbeUpdate) SetStatus(v string) *AccountEndpointProbeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableStatus(v *string) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProbedAt sets the "probed_at" field.
func (_u *AccountEndpointProbeUpdate) SetProbedAt(v time.Time) *AccountEndpointProbeUpdate {
	_u.mutation.SetProbedAt(v)
	return _u
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableProbedAt(v *time.Time) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetProbedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AccountEndpointProbeUpdate) SetExpiresAt(v time.Time) *AccountEndpointProbeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableExpiresAt(v *time.Time) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetEvidenceRef sets the "evidence_ref" field.
func (_u *AccountEndpointProbeUpdate) SetEvidenceRef(v string) *AccountEndpointProbeUpdate {
	_u.mutation.SetEvidenceRef(v)
	return _u
}

// SetNillableEvidenceRef sets the "evidence_ref" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableEvidenceRef(v *string) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetEvidenceRef(*v)
	}
	return _u
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (_u *AccountEndpointProbeUpdate) ClearEvidenceRef() *AccountEndpointProbeUpdate {
	_u.mutation.ClearEvidenceRef()
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *AccountEndpointProbeUpdate) SetRequestFingerprint(v string) *AccountEndpointProbeUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdate) SetNillableRequestFingerprint(v *string) *AccountEndpointProbeUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (_u *AccountEndpointProbeUpdate) ClearRequestFingerprint() *AccountEndpointProbeUpdate {
	_u.mutation.ClearRequestFingerprint()
	return _u
}

// SetResponseSummary sets the "response_summary" field.
func (_u *AccountEndpointProbeUpdate) SetResponseSummary(v map[string]interface{}) *AccountEndpointProbeUpdate {
	_u.mutation.SetResponseSummary(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountEndpointProbeUpdate) SetAccount(v *Account) *AccountEndpointProbeUpdate {
	return _u.SetAccountID(v.ID)
}

// SetConnection sets the "connection" edge to the UpstreamConnection entity.
func (_u *AccountEndpointProbeUpdate) SetConnection(v *UpstreamConnection) *AccountEndpointProbeUpdate {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the AccountEndpointProbeMutation object of the builder.
func (_u *AccountEndpointProbeUpdate) Mutation() *AccountEndpointProbeMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountEndpointProbeUpdate) ClearAccount() *AccountEndpointProbeUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearConnection clears the "connection" edge to the UpstreamConnection entity.
func (_u *AccountEndpointProbeUpdate) ClearConnection() *AccountEndpointProbeUpdate {
	_u.mutation.ClearConnection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountEndpointProbeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountEndpointProbeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountEndpointProbeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountEndpointProbeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountEndpointProbeUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountendpointprobe.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := accountendpointprobe.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedEndpointPath(); ok {
		if err := accountendpointprobe.NormalizedEndpointPathValidator(v); err != nil {
			return &ValidationError{Name: "normalized_endpoint_path", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.normalized_endpoint_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountendpointprobe.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEndpointProbe.account"`)
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEndpointProbe.connection"`)
	}
	return nil
}

func (_u *AccountEndpointProbeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountendpointprobe.Table, accountendpointprobe.Columns, sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountendpointprobe.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(accountendpointprobe.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedEndpointPath(); ok {
		_spec.SetField(accountendpointprobe.FieldNormalizedEndpointPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialVersion(); ok {
		_spec.SetField(accountendpointprobe.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCredentialVersion(); ok {
		_spec.AddField(accountendpointprobe.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(accountendpointprobe.FieldConfigVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(accountendpointprobe.FieldConfigVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountendpointprobe.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbedAt(); ok {
		_spec.SetField(accountendpointprobe.FieldProbedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(accountendpointprobe.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EvidenceRef(); ok {
		_spec.SetField(accountendpointprobe.FieldEvidenceRef, field.TypeString, value)
	}
	if _u.mutation.EvidenceRefCleared() {
		_spec.ClearField(accountendpointprobe.FieldEvidenceRef, field.TypeString)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(accountendpointprobe.FieldRequestFingerprint, field.TypeString, value)
	}
	if _u.mutation.RequestFingerprintCleared() {
		_spec.ClearField(accountendpointprobe.FieldRequestFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseSummary(); ok {
		_spec.SetField(accountendpointprobe.FieldResponseSummary, field.TypeJSON, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.AccountTable,
			Columns: []string{accountendpointprobe.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.AccountTable,
			Columns: []string{accountendpointprobe.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.ConnectionTable,
			Columns: []string{accountendpointprobe.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.ConnectionTable,
			Columns: []string{accountendpointprobe.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountendpointprobe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountEndpointProbeUpdateOne is the builder for updating a single AccountEndpointProbe entity.
type AccountEndpointProbeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountEndpointProbeMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountEndpointProbeUpdateOne) SetAccountID(v int64) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableAccountID(v *int64) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *AccountEndpointProbeUpdateOne) SetConnectionID(v int64) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableConnectionID(v *int64) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountEndpointProbeUpdateOne) SetProvider(v string) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableProvider(v *string) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *AccountEndpointProbeUpdateOne) SetProtocol(v string) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableProtocol(v *string) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetNormalizedEndpointPath sets the "normalized_endpoint_path" field.
func (_u *AccountEndpointProbeUpdateOne) SetNormalizedEndpointPath(v string) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetNormalizedEndpointPath(v)
	return _u
}

// SetNillableNormalizedEndpointPath sets the "normalized_endpoint_path" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableNormalizedEndpointPath(v *string) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetNormalizedEndpointPath(*v)
	}
	return _u
}

// SetCredentialVersion sets the "credential_version" field.
func (_u *AccountEndpointProbeUpdateOne) SetCredentialVersion(v int64) *AccountEndpointProbeUpdateOne {
	_u.mutation.ResetCredentialVersion()
	_u.mutation.SetCredentialVersion(v)
	return _u
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableCredentialVersion(v *int64) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetCredentialVersion(*v)
	}
	return _u
}

// AddCredentialVersion adds value to the "credential_version" field.
func (_u *AccountEndpointProbeUpdateOne) AddCredentialVersion(v int64) *AccountEndpointProbeUpdateOne {
	_u.mutation.AddCredentialVersion(v)
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *AccountEndpointProbeUpdateOne) SetConfigVersion(v int64) *AccountEndpointProbeUpdateOne {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableConfigVersion(v *int64) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *AccountEndpointProbeUpdateOne) AddConfigVersion(v int64) *AccountEndpointProbeUpdateOne {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountEndpointProbeUpdateOne) SetStatus(v string) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableStatus(v *string) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProbedAt sets the "probed_at" field.
func (_u *AccountEndpointProbeUpdateOne) SetProbedAt(v time.Time) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetProbedAt(v)
	return _u
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableProbedAt(v *time.Time) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetProbedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AccountEndpointProbeUpdateOne) SetExpiresAt(v time.Time) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableExpiresAt(v *time.Time) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetEvidenceRef sets the "evidence_ref" field.
func (_u *AccountEndpointProbeUpdateOne) SetEvidenceRef(v string) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetEvidenceRef(v)
	return _u
}

// SetNillableEvidenceRef sets the "evidence_ref" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableEvidenceRef(v *string) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetEvidenceRef(*v)
	}
	return _u
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (_u *AccountEndpointProbeUpdateOne) ClearEvidenceRef() *AccountEndpointProbeUpdateOne {
	_u.mutation.ClearEvidenceRef()
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *AccountEndpointProbeUpdateOne) SetRequestFingerprint(v string) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *AccountEndpointProbeUpdateOne) SetNillableRequestFingerprint(v *string) *AccountEndpointProbeUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (_u *AccountEndpointProbeUpdateOne) ClearRequestFingerprint() *AccountEndpointProbeUpdateOne {
	_u.mutation.ClearRequestFingerprint()
	return _u
}

// SetResponseSummary sets the "response_summary" field.
func (_u *AccountEndpointProbeUpdateOne) SetResponseSummary(v map[string]interface{}) *AccountEndpointProbeUpdateOne {
	_u.mutation.SetResponseSummary(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountEndpointProbeUpdateOne) SetAccount(v *Account) *AccountEndpointProbeUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetConnection sets the "connection" edge to the UpstreamConnection entity.
func (_u *AccountEndpointProbeUpdateOne) SetConnection(v *UpstreamConnection) *AccountEndpointProbeUpdateOne {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the AccountEndpointProbeMutation object of the builder.
func (_u *AccountEndpointProbeUpdateOne) Mutation() *AccountEndpointProbeMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountEndpointProbeUpdateOne) ClearAccount() *AccountEndpointProbeUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearConnection clears the "connection" edge to the UpstreamConnection entity.
func (_u *AccountEndpointProbeUpdateOne) ClearConnection() *AccountEndpointProbeUpdateOne {
	_u.mutation.ClearConnection()
	return _u
}

// Where appends a list predicates to the AccountEndpointProbeUpdate builder.
func (_u *AccountEndpointProbeUpdateOne) Where(ps ...predicate.AccountEndpointProbe) *AccountEndpointProbeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountEndpointProbeUpdateOne) Select(field string, fields ...string) *AccountEndpointProbeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountEndpointProbe entity.
func (_u *AccountEndpointProbeUpdateOne) Save(ctx context.Context) (*AccountEndpointProbe, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountEndpointProbeUpdateOne) SaveX(ctx context.Context) *AccountEndpointProbe {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountEndpointProbeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountEndpointProbeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountEndpointProbeUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountendpointprobe.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := accountendpointprobe.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedEndpointPath(); ok {
		if err := accountendpointprobe.NormalizedEndpointPathValidator(v); err != nil {
			return &ValidationError{Name: "normalized_endpoint_path", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.normalized_endpoint_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountendpointprobe.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEndpointProbe.account"`)
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEndpointProbe.connection"`)
	}
	return nil
}

func (_u *AccountEndpointProbeUpdateOne) sqlSave(ctx context.Context) (_node *AccountEndpointProbe, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountendpointprobe.Table, accountendpointprobe.Columns, sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountEndpointProbe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountendpointprobe.FieldID)
		for _, f := range fields {
			if !accountendpointprobe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountendpointprobe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountendpointprobe.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(accountendpointprobe.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedEndpointPath(); ok {
		_spec.SetField(accountendpointprobe.FieldNormalizedEndpointPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialVersion(); ok {
		_spec.SetField(accountendpointprobe.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCredentialVersion(); ok {
		_spec.AddField(accountendpointprobe.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(accountendpointprobe.FieldConfigVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(accountendpointprobe.FieldConfigVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountendpointprobe.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbedAt(); ok {
		_spec.SetField(accountendpointprobe.FieldProbedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(accountendpointprobe.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EvidenceRef(); ok {
		_spec.SetField(accountendpointprobe.FieldEvidenceRef, field.TypeString, value)
	}
	if _u.mutation.EvidenceRefCleared() {
		_spec.ClearField(accountendpointprobe.FieldEvidenceRef, field.TypeString)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(accountendpointprobe.FieldRequestFingerprint, field.TypeString, value)
	}
	if _u.mutation.RequestFingerprintCleared() {
		_spec.ClearField(accountendpointprobe.FieldRequestFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseSummary(); ok {
		_spec.SetField(accountendpointprobe.FieldResponseSummary, field.TypeJSON, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.AccountTable,
			Columns: []string{accountendpointprobe.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.AccountTable,
			Columns: []string{accountendpointprobe.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.ConnectionTable,
			Columns: []string{accountendpointprobe.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.ConnectionTable,
			Columns: []string{accountendpointprobe.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountEndpointProbe{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountendpointprobe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
