// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountendpointprobe"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// AccountEndpointProbeCreate is the builder for creating a AccountEndpointProbe entity.
type AccountEndpointProbeCreate struct {
	config
	mutation *AccountEndpointProbeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountEndpointProbeCreate) SetAccountID(v int64) *AccountEndpointProbeCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetConnectionID sets the "connection_id" field.
func (_c *AccountEndpointProbeCreate) SetConnectionID(v int64) *AccountEndpointProbeCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AccountEndpointProbeCreate) SetProvider(v string) *AccountEndpointProbeCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *AccountEndpointProbeCreate) SetProtocol(v string) *AccountEndpointProbeCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNormalizedEndpointPath sets the "normalized_endpoint_path" field.
func (_c *AccountEndpointProbeCreate) SetNormalizedEndpointPath(v string) *AccountEndpointProbeCreate {
	_c.mutation.SetNormalizedEndpointPath(v)
	return _c
}

// SetCredentialVersion sets the "credential_version" field.
func (_c *AccountEndpointProbeCreate) SetCredentialVersion(v int64) *AccountEndpointProbeCreate {
	_c.mutation.SetCredentialVersion(v)
	return _c
}

// SetConfigVersion sets the "config_version" field.
func (_c *AccountEndpointProbeCreate) SetConfigVersion(v int64) *AccountEndpointProbeCreate {
	_c.mutation.SetConfigVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountEndpointProbeCreate) SetStatus(v string) *AccountEndpointProbeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetProbedAt sets the "probed_at" field.
func (_c *AccountEndpointProbeCreate) SetProbedAt(v time.Time) *AccountEndpointProbeCreate {
	_c.mutation.SetProbedAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AccountEndpointProbeCreate) SetExpiresAt(v time.Time) *AccountEndpointProbeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetEvidenceRef sets the "evidence_ref" field.
func (_c *AccountEndpointProbeCreate) SetEvidenceRef(v string) *AccountEndpointProbeCreate {
	_c.mutation.SetEvidenceRef(v)
	return _c
}

// SetNillableEvidenceRef sets the "evidence_ref" field if the given value is not nil.
func (_c *AccountEndpointProbeCreate) SetNillableEvidenceRef(v *string) *AccountEndpointProbeCreate {
	if v != nil {
		_c.SetEvidenceRef(*v)
	}
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *AccountEndpointProbeCreate) SetRequestFingerprint(v string) *AccountEndpointProbeCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_c *AccountEndpointProbeCreate) SetNillableRequestFingerprint(v *string) *AccountEndpointProbeCreate {
	if v != nil {
		_c.SetRequestFingerprint(*v)
	}
	return _c
}

// SetResponseSummary sets the "response_summary" field.
func (_c *AccountEndpointProbeCreate) SetResponseSummary(v map[string]interface{}) *AccountEndpointProbeCreate {
	_c.mutation.SetResponseSummary(v)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountEndpointProbeCreate) SetAccount(v *Account) *AccountEndpointProbeCreate {
	return _c.SetAccountID(v.ID)
}

// SetConnection sets the "connection" edge to the UpstreamConnection entity.
func (_c *AccountEndpointProbeCreate) SetConnection(v *UpstreamConnection) *AccountEndpointProbeCreate {
	return _c.SetConnectionID(v.ID)
}

// Mutation returns the AccountEndpointProbeMutation object of the builder.
func (_c *AccountEndpointProbeCreate) Mutation() *AccountEndpointProbeMutation {
	return _c.mutation
}

// Save creates the AccountEndpointProbe in the database.
func (_c *AccountEndpointProbeCreate) Save(ctx context.Context) (*AccountEndpointProbe, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountEndpointProbeCreate) SaveX(ctx context.Context) *AccountEndpointProbe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountEndpointProbeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountEndpointProbeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountEndpointProbeCreate) defaults() {
	if _, ok := _c.mutation.ResponseSummary(); !ok {
		v := accountendpointprobe.DefaultResponseSummary()
		_c.mutation.SetResponseSummary(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountEndpointProbeCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountEndpointProbe.account_id"`)}
	}
	if _, ok := _c.mutation.ConnectionID(); !ok {
		return &ValidationError{Name: "connection_id", err: errors.New(`ent: missing required field "AccountEndpointProbe.connection_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AccountEndpointProbe.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := accountendpointprobe.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "AccountEndpointProbe.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := accountendpointprobe.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedEndpointPath(); !ok {
		return &ValidationError{Name: "normalized_endpoint_path", err: errors.New(`ent: missing required field "AccountEndpointProbe.normalized_endpoint_path"`)}
	}
	if v, ok := _c.mutation.NormalizedEndpointPath(); ok {
		if err := accountendpointprobe.NormalizedEndpointPathValidator(v); err != nil {
			return &ValidationError{Name: "normalized_endpoint_path", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.normalized_endpoint_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CredentialVersion(); !ok {
		return &ValidationError{Name: "credential_version", err: errors.New(`ent: missing required field "AccountEndpointProbe.credential_version"`)}
	}
	if _, ok := _c.mutation.ConfigVersion(); !ok {
		return &ValidationError{Name: "config_version", err: errors.New(`ent: missing required field "AccountEndpointProbe.config_version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccountEndpointProbe.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accountendpointprobe.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEndpointProbe.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProbedAt(); !ok {
		return &ValidationError{Name: "probed_at", err: errors.New(`ent: missing required field "AccountEndpointProbe.probed_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AccountEndpointProbe.expires_at"`)}
	}
	if _, ok := _c.mutation.ResponseSummary(); !ok {
		return &ValidationError{Name: "response_summary", err: errors.New(`ent: missing required field "AccountEndpointProbe.response_summary"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountEndpointProbe.account"`)}
	}
	if len(_c.mutation.ConnectionIDs()) == 0 {
		return &ValidationError{Name: "connection", err: errors.New(`ent: missing required edge "AccountEndpointProbe.connection"`)}
	}
	return nil
}

func (_c *AccountEndpointProbeCreate) sqlSave(ctx context.Context) (*AccountEndpointProbe, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountEndpointProbeCreate) createSpec() (*AccountEndpointProbe, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountEndpointProbe{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountendpointprobe.Table, sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(accountendpointprobe.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(accountendpointprobe.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.NormalizedEndpointPath(); ok {
		_spec.SetField(accountendpointprobe.FieldNormalizedEndpointPath, field.TypeString, value)
		_node.NormalizedEndpointPath = value
	}
	if value, ok := _c.mutation.CredentialVersion(); ok {
		_spec.SetField(accountendpointprobe.FieldCredentialVersion, field.TypeInt64, value)
		_node.CredentialVersion = value
	}
	if value, ok := _c.mutation.ConfigVersion(); ok {
		_spec.SetField(accountendpointprobe.FieldConfigVersion, field.TypeInt64, value)
		_node.ConfigVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accountendpointprobe.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProbedAt(); ok {
		_spec.SetField(accountendpointprobe.FieldProbedAt, field.TypeTime, value)
		_node.ProbedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(accountendpointprobe.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.EvidenceRef(); ok {
		_spec.SetField(accountendpointprobe.FieldEvidenceRef, field.TypeString, value)
		_node.EvidenceRef = &value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(accountendpointprobe.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = &value
	}
	if value, ok := _c.mutation.ResponseSummary(); ok {
		_spec.SetField(accountendpointprobe.FieldResponseSummary, field.TypeJSON, value)
		_node.ResponseSummary = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.AccountTable,
			Columns: []string{accountendpointprobe.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountendpointprobe.ConnectionTable,
			Columns: []string{accountendpointprobe.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConnectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountEndpointProbe.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountEndpointProbeUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountEndpointProbeCreate) OnConflict(opts ...sql.ConflictOption) *AccountEndpointProbeUpsertOne {
	_c.conflict = opts
	return &AccountEndpointProbeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountEndpointProbe.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountEndpointProbeCreate) OnConflictColumns(columns ...string) *AccountEndpointProbeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountEndpointProbeUpsertOne{
		create: _c,
	}
}

type (
	// AccountEndpointProbeUpsertOne is the builder for "upsert"-ing
	//  one AccountEndpointProbe node.
	AccountEndpointProbeUpsertOne struct {
		create *AccountEndpointProbeCreate
	}

	// AccountEndpointProbeUpsert is the "OnConflict" setter.
	AccountEndpointProbeUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountEndpointProbeUpsert) SetAccountID(v int64) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateAccountID() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldAccountID)
	return u
}

// SetConnectionID sets the "connection_id" field.
func (u *AccountEndpointProbeUpsert) SetConnectionID(v int64) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldConnectionID, v)
	return u
}

// UpdateConnectionID sets the "connection_id" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateConnectionID() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldConnectionID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AccountEndpointProbeUpsert) SetProvider(v string) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateProvider() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldProvider)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *AccountEndpointProbeUpsert) SetProtocol(v string) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateProtocol() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldProtocol)
	return u
}

// SetNormalizedEndpointPath sets the "normalized_endpoint_path" field.
func (u *AccountEndpointProbeUpsert) SetNormalizedEndpointPath(v string) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldNormalizedEndpointPath, v)
	return u
}

// UpdateNormalizedEndpointPath sets the "normalized_endpoint_path" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateNormalizedEndpointPath() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldNormalizedEndpointPath)
	return u
}

// SetCredentialVersion sets the "credential_version" field.
func (u *AccountEndpointProbeUpsert) SetCredentialVersion(v int64) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldCredentialVersion, v)
	return u
}

// UpdateCredentialVersion sets the "credential_version" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateCredentialVersion() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldCredentialVersion)
	return u
}

// AddCredentialVersion adds v to the "credential_version" field.
func (u *AccountEndpointProbeUpsert) AddCredentialVersion(v int64) *AccountEndpointProbeUpsert {
	u.Add(accountendpointprobe.FieldCredentialVersion, v)
	return u
}

// SetConfigVersion sets the "config_version" field.
func (u *AccountEndpointProbeUpsert) SetConfigVersion(v int64) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldConfigVersion, v)
	return u
}

// UpdateConfigVersion sets the "config_version" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateConfigVersion() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldConfigVersion)
	return u
}

// AddConfigVersion adds v to the "config_version" field.
func (u *AccountEndpointProbeUpsert) AddConfigVersion(v int64) *AccountEndpointProbeUpsert {
	u.Add(accountendpointprobe.FieldConfigVersion, v)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountEndpointProbeUpsert) SetStatus(v string) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateStatus() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldStatus)
	return u
}

// SetProbedAt sets the "probed_at" field.
func (u *AccountEndpointProbeUpsert) SetProbedAt(v time.Time) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldProbedAt, v)
	return u
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateProbedAt() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldProbedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountEndpointProbeUpsert) SetExpiresAt(v time.Time) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateExpiresAt() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldExpiresAt)
	return u
}

// SetEvidenceRef sets the "evidence_ref" field.
func (u *AccountEndpointProbeUpsert) SetEvidenceRef(v string) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldEvidenceRef, v)
	return u
}

// UpdateEvidenceRef sets the "evidence_ref" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateEvidenceRef() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldEvidenceRef)
	return u
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (u *AccountEndpointProbeUpsert) ClearEvidenceRef() *AccountEndpointProbeUpsert {
	u.SetNull(accountendpointprobe.FieldEvidenceRef)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *AccountEndpointProbeUpsert) SetRequestFingerprint(v string) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateRequestFingerprint() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldRequestFingerprint)
	return u
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (u *AccountEndpointProbeUpsert) ClearRequestFingerprint() *AccountEndpointProbeUpsert {
	u.SetNull(accountendpointprobe.FieldRequestFingerprint)
	return u
}

// SetResponseSummary sets the "response_summary" field.
func (u *AccountEndpointProbeUpsert) SetResponseSummary(v map[string]interface{}) *AccountEndpointProbeUpsert {
	u.Set(accountendpointprobe.FieldResponseSummary, v)
	return u
}

// UpdateResponseSummary sets the "response_summary" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsert) UpdateResponseSummary() *AccountEndpointProbeUpsert {
	u.SetExcluded(accountendpointprobe.FieldResponseSummary)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountEndpointProbe.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountEndpointProbeUpsertOne) UpdateNewValues() *AccountEndpointProbeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountEndpointProbe.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountEndpointProbeUpsertOne) Ignore() *AccountEndpointProbeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountEndpointProbeUpsertOne) DoNothing() *AccountEndpointProbeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountEndpointProbeCreate.OnConflict
// documentation for more info.
func (u *AccountEndpointProbeUpsertOne) Update(set func(*AccountEndpointProbeUpsert)) *AccountEndpointProbeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountEndpointProbeUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountEndpointProbeUpsertOne) SetAccountID(v int64) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateAccountID() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateAccountID()
	})
}

// SetConnectionID sets the "connection_id" field.
func (u *AccountEndpointProbeUpsertOne) SetConnectionID(v int64) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetConnectionID(v)
	})
}

// UpdateConnectionID sets the "connection_id" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateConnectionID() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateConnectionID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountEndpointProbeUpsertOne) SetProvider(v string) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateProvider() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateProvider()
	})
}

// SetProtocol sets the "protocol" field.
func (u *AccountEndpointProbeUpsertOne) SetProtocol(v string) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateProtocol() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateProtocol()
	})
}

// SetNormalizedEndpointPath sets the "normalized_endpoint_path" field.
func (u *AccountEndpointProbeUpsertOne) SetNormalizedEndpointPath(v string) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetNormalizedEndpointPath(v)
	})
}

// UpdateNormalizedEndpointPath sets the "normalized_endpoint_path" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateNormalizedEndpointPath() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateNormalizedEndpointPath()
	})
}

// SetCredentialVersion sets the "credential_version" field.
func (u *AccountEndpointProbeUpsertOne) SetCredentialVersion(v int64) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetCredentialVersion(v)
	})
}

// AddCredentialVersion adds v to the "credential_version" field.
func (u *AccountEndpointProbeUpsertOne) AddCredentialVersion(v int64) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.AddCredentialVersion(v)
	})
}

// UpdateCredentialVersion sets the "credential_version" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateCredentialVersion() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateCredentialVersion()
	})
}

// SetConfigVersion sets the "config_version" field.
func (u *AccountEndpointProbeUpsertOne) SetConfigVersion(v int64) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetConfigVersion(v)
	})
}

// AddConfigVersion adds v to the "config_version" field.
func (u *AccountEndpointProbeUpsertOne) AddConfigVersion(v int64) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.AddConfigVersion(v)
	})
}

// UpdateConfigVersion sets the "config_version" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateConfigVersion() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateConfigVersion()
	})
}

// SetStatus sets the "status" field.
func (u *AccountEndpointProbeUpsertOne) SetStatus(v string) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateStatus() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateStatus()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *AccountEndpointProbeUpsertOne) SetProbedAt(v time.Time) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateProbedAt() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateProbedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountEndpointProbeUpsertOne) SetExpiresAt(v time.Time) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateExpiresAt() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetEvidenceRef sets the "evidence_ref" field.
func (u *AccountEndpointProbeUpsertOne) SetEvidenceRef(v string) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetEvidenceRef(v)
	})
}

// UpdateEvidenceRef sets the "evidence_ref" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateEvidenceRef() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateEvidenceRef()
	})
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (u *AccountEndpointProbeUpsertOne) ClearEvidenceRef() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.ClearEvidenceRef()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *AccountEndpointProbeUpsertOne) SetRequestFingerprint(v string) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateRequestFingerprint() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (u *AccountEndpointProbeUpsertOne) ClearRequestFingerprint() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.ClearRequestFingerprint()
	})
}

// SetResponseSummary sets the "response_summary" field.
func (u *AccountEndpointProbeUpsertOne) SetResponseSummary(v map[string]interface{}) *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetResponseSummary(v)
	})
}

// UpdateResponseSummary sets the "response_summary" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertOne) UpdateResponseSummary() *AccountEndpointProbeUpsertOne {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateResponseSummary()
	})
}

// Exec executes the query.
func (u *AccountEndpointProbeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountEndpointProbeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountEndpointProbeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountEndpointProbeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountEndpointProbeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountEndpointProbeCreateBulk is the builder for creating many AccountEndpointProbe entities in bulk.
type AccountEndpointProbeCreateBulk struct {
	config
	err      error
	builders []*AccountEndpointProbeCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountEndpointProbe entities in the database.
func (_c *AccountEndpointProbeCreateBulk) Save(ctx context.Context) ([]*AccountEndpointProbe, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountEndpointProbe, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountEndpointProbeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountEndpointProbeCreateBulk) SaveX(ctx context.Context) []*AccountEndpointProbe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountEndpointProbeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountEndpointProbeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountEndpointProbe.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountEndpointProbeUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountEndpointProbeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountEndpointProbeUpsertBulk {
	_c.conflict = opts
	return &AccountEndpointProbeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountEndpointProbe.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountEndpointProbeCreateBulk) OnConflictColumns(columns ...string) *AccountEndpointProbeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountEndpointProbeUpsertBulk{
		create: _c,
	}
}

// AccountEndpointProbeUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountEndpointProbe nodes.
type AccountEndpointProbeUpsertBulk struct {
	create *AccountEndpointProbeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountEndpointProbe.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountEndpointProbeUpsertBulk) UpdateNewValues() *AccountEndpointProbeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountEndpointProbe.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountEndpointProbeUpsertBulk) Ignore() *AccountEndpointProbeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountEndpointProbeUpsertBulk) DoNothing() *AccountEndpointProbeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountEndpointProbeCreateBulk.OnConflict
// documentation for more info.
func (u *AccountEndpointProbeUpsertBulk) Update(set func(*AccountEndpointProbeUpsert)) *AccountEndpointProbeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountEndpointProbeUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountEndpointProbeUpsertBulk) SetAccountID(v int64) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateAccountID() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateAccountID()
	})
}

// SetConnectionID sets the "connection_id" field.
func (u *AccountEndpointProbeUpsertBulk) SetConnectionID(v int64) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetConnectionID(v)
	})
}

// UpdateConnectionID sets the "connection_id" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateConnectionID() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateConnectionID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountEndpointProbeUpsertBulk) SetProvider(v string) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateProvider() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateProvider()
	})
}

// SetProtocol sets the "protocol" field.
func (u *AccountEndpointProbeUpsertBulk) SetProtocol(v string) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateProtocol() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateProtocol()
	})
}

// SetNormalizedEndpointPath sets the "normalized_endpoint_path" field.
func (u *AccountEndpointProbeUpsertBulk) SetNormalizedEndpointPath(v string) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetNormalizedEndpointPath(v)
	})
}

// UpdateNormalizedEndpointPath sets the "normalized_endpoint_path" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateNormalizedEndpointPath() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateNormalizedEndpointPath()
	})
}

// SetCredentialVersion sets the "credential_version" field.
func (u *AccountEndpointProbeUpsertBulk) SetCredentialVersion(v int64) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetCredentialVersion(v)
	})
}

// AddCredentialVersion adds v to the "credential_version" field.
func (u *AccountEndpointProbeUpsertBulk) AddCredentialVersion(v int64) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.AddCredentialVersion(v)
	})
}

// UpdateCredentialVersion sets the "credential_version" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateCredentialVersion() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateCredentialVersion()
	})
}

// SetConfigVersion sets the "config_version" field.
func (u *AccountEndpointProbeUpsertBulk) SetConfigVersion(v int64) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetConfigVersion(v)
	})
}

// AddConfigVersion adds v to the "config_version" field.
func (u *AccountEndpointProbeUpsertBulk) AddConfigVersion(v int64) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.AddConfigVersion(v)
	})
}

// UpdateConfigVersion sets the "config_version" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateConfigVersion() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateConfigVersion()
	})
}

// SetStatus sets the "status" field.
func (u *AccountEndpointProbeUpsertBulk) SetStatus(v string) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateStatus() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateStatus()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *AccountEndpointProbeUpsertBulk) SetProbedAt(v time.Time) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateProbedAt() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateProbedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountEndpointProbeUpsertBulk) SetExpiresAt(v time.Time) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateExpiresAt() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetEvidenceRef sets the "evidence_ref" field.
func (u *AccountEndpointProbeUpsertBulk) SetEvidenceRef(v string) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetEvidenceRef(v)
	})
}

// UpdateEvidenceRef sets the "evidence_ref" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateEvidenceRef() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateEvidenceRef()
	})
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (u *AccountEndpointProbeUpsertBulk) ClearEvidenceRef() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.ClearEvidenceRef()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *AccountEndpointProbeUpsertBulk) SetRequestFingerprint(v string) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateRequestFingerprint() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (u *AccountEndpointProbeUpsertBulk) ClearRequestFingerprint() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.ClearRequestFingerprint()
	})
}

// SetResponseSummary sets the "response_summary" field.
func (u *AccountEndpointProbeUpsertBulk) SetResponseSummary(v map[string]interface{}) *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.SetResponseSummary(v)
	})
}

// UpdateResponseSummary sets the "response_summary" field to the value that was provided on create.
func (u *AccountEndpointProbeUpsertBulk) UpdateResponseSummary() *AccountEndpointProbeUpsertBulk {
	return u.Update(func(s *AccountEndpointProbeUpsert) {
		s.UpdateResponseSummary()
	})
}

// Exec executes the query.
func (u *AccountEndpointProbeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountEndpointProbeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountEndpointProbeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountEndpointProbeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
