// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountendpointprobe"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// AccountEndpointProbe is the model entity for the AccountEndpointProbe schema.
type AccountEndpointProbe struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// FK to accounts
	AccountID int64 `json:"account_id,omitempty"`
	// FK to upstream_connections
	ConnectionID int64 `json:"connection_id,omitempty"`
	// governed provider
	Provider string `json:"provider,omitempty"`
	// anthropic | openai | gemini
	Protocol string `json:"protocol,omitempty"`
	// NormalizedEndpointPath holds the value of the "normalized_endpoint_path" field.
	NormalizedEndpointPath string `json:"normalized_endpoint_path,omitempty"`
	// >0
	CredentialVersion int64 `json:"credential_version,omitempty"`
	// >0
	ConfigVersion int64 `json:"config_version,omitempty"`
	// success or failed
	Status string `json:"status,omitempty"`
	// ProbedAt holds the value of the "probed_at" field.
	ProbedAt time.Time `json:"probed_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// EvidenceRef holds the value of the "evidence_ref" field.
	EvidenceRef *string `json:"evidence_ref,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint *string `json:"request_fingerprint,omitempty"`
	// ResponseSummary holds the value of the "response_summary" field.
	ResponseSummary map[string]interface{} `json:"response_summary,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountEndpointProbeQuery when eager-loading is set.
	Edges        AccountEndpointProbeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountEndpointProbeEdges holds the relations/edges for other nodes in the graph.
type AccountEndpointProbeEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Connection holds the value of the connection edge.
	Connection *UpstreamConnection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEndpointProbeEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEndpointProbeEdges) ConnectionOrErr() (*UpstreamConnection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: upstreamconnection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountEndpointProbe) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountendpointprobe.FieldResponseSummary:
			values[i] = new([]byte)
		case accountendpointprobe.FieldID, accountendpointprobe.FieldAccountID, accountendpointprobe.FieldConnectionID, accountendpointprobe.FieldCredentialVersion, accountendpointprobe.FieldConfigVersion:
			values[i] = new(sql.NullInt64)
		case accountendpointprobe.FieldProvider, accountendpointprobe.FieldProtocol, accountendpointprobe.FieldNormalizedEndpointPath, accountendpointprobe.FieldStatus, accountendpointprobe.FieldEvidenceRef, accountendpointprobe.FieldRequestFingerprint:
			values[i] = new(sql.NullString)
		case accountendpointprobe.FieldProbedAt, accountendpointprobe.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountEndpointProbe fields.
func (_m *AccountEndpointProbe) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountendpointprobe.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountendpointprobe.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountendpointprobe.FieldConnectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = value.Int64
			}
		case accountendpointprobe.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case accountendpointprobe.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case accountendpointprobe.FieldNormalizedEndpointPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_endpoint_path", values[i])
			} else if value.Valid {
				_m.NormalizedEndpointPath = value.String
			}
		case accountendpointprobe.FieldCredentialVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credential_version", values[i])
			} else if value.Valid {
				_m.CredentialVersion = value.Int64
			}
		case accountendpointprobe.FieldConfigVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field config_version", values[i])
			} else if value.Valid {
				_m.ConfigVersion = value.Int64
			}
		case accountendpointprobe.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case accountendpointprobe.FieldProbedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field probed_at", values[i])
			} else if value.Valid {
				_m.ProbedAt = value.Time
			}
		case accountendpointprobe.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case accountendpointprobe.FieldEvidenceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field evidence_ref", values[i])
			} else if value.Valid {
				_m.EvidenceRef = new(string)
				*_m.EvidenceRef = value.String
			}
		case accountendpointprobe.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = new(string)
				*_m.RequestFingerprint = value.String
			}
		case accountendpointprobe.FieldResponseSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseSummary); err != nil {
					return fmt.Errorf("unmarshal field response_summary: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountEndpointProbe.
// This includes values selected through modifiers, order, etc.
func (_m *AccountEndpointProbe) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountEndpointProbe entity.
func (_m *AccountEndpointProbe) QueryAccount() *AccountQuery {
	return NewAccountEndpointProbeClient(_m.config).QueryAccount(_m)
}

// QueryConnection queries the "connection" edge of the AccountEndpointProbe entity.
func (_m *AccountEndpointProbe) QueryConnection() *UpstreamConnectionQuery {
	return NewAccountEndpointProbeClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this AccountEndpointProbe.
// Note that you need to call AccountEndpointProbe.Unwrap() before calling this method if this AccountEndpointProbe
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountEndpointProbe) Update() *AccountEndpointProbeUpdateOne {
	return NewAccountEndpointProbeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountEndpointProbe entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountEndpointProbe) Unwrap() *AccountEndpointProbe {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountEndpointProbe is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountEndpointProbe) String() string {
	var builder strings.Builder
	builder.WriteString("AccountEndpointProbe(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("connection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConnectionID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("normalized_endpoint_path=")
	builder.WriteString(_m.NormalizedEndpointPath)
	builder.WriteString(", ")
	builder.WriteString("credential_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialVersion))
	builder.WriteString(", ")
	builder.WriteString("config_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigVersion))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("probed_at=")
	builder.WriteString(_m.ProbedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EvidenceRef; v != nil {
		builder.WriteString("evidence_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestFingerprint; v != nil {
		builder.WriteString("request_fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("response_summary=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseSummary))
	builder.WriteByte(')')
	return builder.String()
}

// AccountEndpointProbes is a parsable slice of AccountEndpointProbe.
type AccountEndpointProbes []*AccountEndpointProbe
