// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountendpointprobe"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// UpstreamConnectionCreate is the builder for creating a UpstreamConnection entity.
type UpstreamConnectionCreate struct {
	config
	mutation *UpstreamConnectionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamConnectionCreate) SetCreatedAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableCreatedAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamConnectionCreate) SetUpdatedAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamConnectionCreate) SetDeletedAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableDeletedAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *UpstreamConnectionCreate) SetKind(v string) *UpstreamConnectionCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UpstreamConnectionCreate) SetProvider(v string) *UpstreamConnectionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableProvider(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamConnectionCreate) SetBaseURL(v string) *UpstreamConnectionCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetEncryptedCredential sets the "encrypted_credential" field.
func (_c *UpstreamConnectionCreate) SetEncryptedCredential(v string) *UpstreamConnectionCreate {
	_c.mutation.SetEncryptedCredential(v)
	return _c
}

// SetCredentialVersion sets the "credential_version" field.
func (_c *UpstreamConnectionCreate) SetCredentialVersion(v int64) *UpstreamConnectionCreate {
	_c.mutation.SetCredentialVersion(v)
	return _c
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableCredentialVersion(v *int64) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetCredentialVersion(*v)
	}
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *UpstreamConnectionCreate) SetProxyID(v int64) *UpstreamConnectionCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableProxyID(v *int64) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamConnectionCreate) SetStatus(v string) *UpstreamConnectionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableStatus(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEvidenceRef sets the "evidence_ref" field.
func (_c *UpstreamConnectionCreate) SetEvidenceRef(v string) *UpstreamConnectionCreate {
	_c.mutation.SetEvidenceRef(v)
	return _c
}

// SetNillableEvidenceRef sets the "evidence_ref" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableEvidenceRef(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetEvidenceRef(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *UpstreamConnectionCreate) AddAccountIDs(ids ...int64) *UpstreamConnectionCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *UpstreamConnectionCreate) AddAccounts(v ...*Account) *UpstreamConnectionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddConnectionProbeIDs adds the "connection_probes" edge to the AccountEndpointProbe entity by IDs.
func (_c *UpstreamConnectionCreate) AddConnectionProbeIDs(ids ...int64) *UpstreamConnectionCreate {
	_c.mutation.AddConnectionProbeIDs(ids...)
	return _c
}

// AddConnectionProbes adds the "connection_probes" edges to the AccountEndpointProbe entity.
func (_c *UpstreamConnectionCreate) AddConnectionProbes(v ...*AccountEndpointProbe) *UpstreamConnectionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConnectionProbeIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *UpstreamConnectionCreate) SetProxy(v *Proxy) *UpstreamConnectionCreate {
	return _c.SetProxyID(v.ID)
}

// Mutation returns the UpstreamConnectionMutation object of the builder.
func (_c *UpstreamConnectionCreate) Mutation() *UpstreamConnectionMutation {
	return _c.mutation
}

// Save creates the UpstreamConnection in the database.
func (_c *UpstreamConnectionCreate) Save(ctx context.Context) (*UpstreamConnection, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamConnectionCreate) SaveX(ctx context.Context) *UpstreamConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamConnectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamConnectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamConnectionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstreamconnection.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamconnection.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamconnection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstreamconnection.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamconnection.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamconnection.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CredentialVersion(); !ok {
		v := upstreamconnection.DefaultCredentialVersion
		_c.mutation.SetCredentialVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreamconnection.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamConnectionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamConnection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamConnection.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "UpstreamConnection.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := upstreamconnection.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := upstreamconnection.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "UpstreamConnection.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstreamconnection.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedCredential(); !ok {
		return &ValidationError{Name: "encrypted_credential", err: errors.New(`ent: missing required field "UpstreamConnection.encrypted_credential"`)}
	}
	if v, ok := _c.mutation.EncryptedCredential(); ok {
		if err := upstreamconnection.EncryptedCredentialValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_credential", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.encrypted_credential": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CredentialVersion(); !ok {
		return &ValidationError{Name: "credential_version", err: errors.New(`ent: missing required field "UpstreamConnection.credential_version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamConnection.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamconnection.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.status": %w`, err)}
		}
	}
	return nil
}

func (_c *UpstreamConnectionCreate) sqlSave(ctx context.Context) (*UpstreamConnection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamConnectionCreate) createSpec() (*UpstreamConnection, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamConnection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamconnection.Table, sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamconnection.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(upstreamconnection.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(upstreamconnection.FieldProvider, field.TypeString, value)
		_node.Provider = &value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconnection.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.EncryptedCredential(); ok {
		_spec.SetField(upstreamconnection.FieldEncryptedCredential, field.TypeString, value)
		_node.EncryptedCredential = value
	}
	if value, ok := _c.mutation.CredentialVersion(); ok {
		_spec.SetField(upstreamconnection.FieldCredentialVersion, field.TypeInt64, value)
		_node.CredentialVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamconnection.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EvidenceRef(); ok {
		_spec.SetField(upstreamconnection.FieldEvidenceRef, field.TypeString, value)
		_node.EvidenceRef = &value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConnectionProbesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstreamconnection.ProxyTable,
			Columns: []string{upstreamconnection.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamConnection.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamConnectionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamConnectionCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamConnectionUpsertOne {
	_c.conflict = opts
	return &UpstreamConnectionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamConnectionCreate) OnConflictColumns(columns ...string) *UpstreamConnectionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamConnectionUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamConnectionUpsertOne is the builder for "upsert"-ing
	//  one UpstreamConnection node.
	UpstreamConnectionUpsertOne struct {
		create *UpstreamConnectionCreate
	}

	// UpstreamConnectionUpsert is the "OnConflict" setter.
	UpstreamConnectionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConnectionUpsert) SetUpdatedAt(v time.Time) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateUpdatedAt() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamConnectionUpsert) SetDeletedAt(v time.Time) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateDeletedAt() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamConnectionUpsert) ClearDeletedAt() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldDeletedAt)
	return u
}

// SetKind sets the "kind" field.
func (u *UpstreamConnectionUpsert) SetKind(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateKind() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldKind)
	return u
}

// SetProvider sets the "provider" field.
func (u *UpstreamConnectionUpsert) SetProvider(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateProvider() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *UpstreamConnectionUpsert) ClearProvider() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldProvider)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConnectionUpsert) SetBaseURL(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateBaseURL() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldBaseURL)
	return u
}

// SetEncryptedCredential sets the "encrypted_credential" field.
func (u *UpstreamConnectionUpsert) SetEncryptedCredential(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldEncryptedCredential, v)
	return u
}

// UpdateEncryptedCredential sets the "encrypted_credential" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateEncryptedCredential() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldEncryptedCredential)
	return u
}

// SetCredentialVersion sets the "credential_version" field.
func (u *UpstreamConnectionUpsert) SetCredentialVersion(v int64) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldCredentialVersion, v)
	return u
}

// UpdateCredentialVersion sets the "credential_version" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateCredentialVersion() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldCredentialVersion)
	return u
}

// AddCredentialVersion adds v to the "credential_version" field.
func (u *UpstreamConnectionUpsert) AddCredentialVersion(v int64) *UpstreamConnectionUpsert {
	u.Add(upstreamconnection.FieldCredentialVersion, v)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamConnectionUpsert) SetProxyID(v int64) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateProxyID() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldProxyID)
	return u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamConnectionUpsert) ClearProxyID() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldProxyID)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamConnectionUpsert) SetStatus(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateStatus() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldStatus)
	return u
}

// SetEvidenceRef sets the "evidence_ref" field.
func (u *UpstreamConnectionUpsert) SetEvidenceRef(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldEvidenceRef, v)
	return u
}

// UpdateEvidenceRef sets the "evidence_ref" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateEvidenceRef() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldEvidenceRef)
	return u
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (u *UpstreamConnectionUpsert) ClearEvidenceRef() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldEvidenceRef)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamConnectionUpsertOne) UpdateNewValues() *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamconnection.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamConnectionUpsertOne) Ignore() *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamConnectionUpsertOne) DoNothing() *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamConnectionCreate.OnConflict
// documentation for more info.
func (u *UpstreamConnectionUpsertOne) Update(set func(*UpstreamConnectionUpsert)) *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamConnectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConnectionUpsertOne) SetUpdatedAt(v time.Time) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateUpdatedAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamConnectionUpsertOne) SetDeletedAt(v time.Time) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateDeletedAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamConnectionUpsertOne) ClearDeletedAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetKind sets the "kind" field.
func (u *UpstreamConnectionUpsertOne) SetKind(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateKind() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateKind()
	})
}

// SetProvider sets the "provider" field.
func (u *UpstreamConnectionUpsertOne) SetProvider(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateProvider() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *UpstreamConnectionUpsertOne) ClearProvider() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearProvider()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConnectionUpsertOne) SetBaseURL(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateBaseURL() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateBaseURL()
	})
}

// SetEncryptedCredential sets the "encrypted_credential" field.
func (u *UpstreamConnectionUpsertOne) SetEncryptedCredential(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetEncryptedCredential(v)
	})
}

// UpdateEncryptedCredential sets the "encrypted_credential" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateEncryptedCredential() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateEncryptedCredential()
	})
}

// SetCredentialVersion sets the "credential_version" field.
func (u *UpstreamConnectionUpsertOne) SetCredentialVersion(v int64) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetCredentialVersion(v)
	})
}

// AddCredentialVersion adds v to the "credential_version" field.
func (u *UpstreamConnectionUpsertOne) AddCredentialVersion(v int64) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.AddCredentialVersion(v)
	})
}

// UpdateCredentialVersion sets the "credential_version" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateCredentialVersion() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateCredentialVersion()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamConnectionUpsertOne) SetProxyID(v int64) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateProxyID() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamConnectionUpsertOne) ClearProxyID() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearProxyID()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamConnectionUpsertOne) SetStatus(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateStatus() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateStatus()
	})
}

// SetEvidenceRef sets the "evidence_ref" field.
func (u *UpstreamConnectionUpsertOne) SetEvidenceRef(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetEvidenceRef(v)
	})
}

// UpdateEvidenceRef sets the "evidence_ref" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateEvidenceRef() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateEvidenceRef()
	})
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (u *UpstreamConnectionUpsertOne) ClearEvidenceRef() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearEvidenceRef()
	})
}

// Exec executes the query.
func (u *UpstreamConnectionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamConnectionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamConnectionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamConnectionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamConnectionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamConnectionCreateBulk is the builder for creating many UpstreamConnection entities in bulk.
type UpstreamConnectionCreateBulk struct {
	config
	err      error
	builders []*UpstreamConnectionCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamConnection entities in the database.
func (_c *UpstreamConnectionCreateBulk) Save(ctx context.Context) ([]*UpstreamConnection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamConnection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamConnectionCreateBulk) SaveX(ctx context.Context) []*UpstreamConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamConnection.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamConnectionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamConnectionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamConnectionUpsertBulk {
	_c.conflict = opts
	return &UpstreamConnectionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamConnectionCreateBulk) OnConflictColumns(columns ...string) *UpstreamConnectionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamConnectionUpsertBulk{
		create: _c,
	}
}

// UpstreamConnectionUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamConnection nodes.
type UpstreamConnectionUpsertBulk struct {
	create *UpstreamConnectionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamConnectionUpsertBulk) UpdateNewValues() *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamconnection.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamConnectionUpsertBulk) Ignore() *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamConnectionUpsertBulk) DoNothing() *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamConnectionCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamConnectionUpsertBulk) Update(set func(*UpstreamConnectionUpsert)) *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamConnectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConnectionUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateUpdatedAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamConnectionUpsertBulk) SetDeletedAt(v time.Time) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateDeletedAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamConnectionUpsertBulk) ClearDeletedAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetKind sets the "kind" field.
func (u *UpstreamConnectionUpsertBulk) SetKind(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateKind() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateKind()
	})
}

// SetProvider sets the "provider" field.
func (u *UpstreamConnectionUpsertBulk) SetProvider(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateProvider() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *UpstreamConnectionUpsertBulk) ClearProvider() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearProvider()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConnectionUpsertBulk) SetBaseURL(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateBaseURL() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateBaseURL()
	})
}

// SetEncryptedCredential sets the "encrypted_credential" field.
func (u *UpstreamConnectionUpsertBulk) SetEncryptedCredential(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetEncryptedCredential(v)
	})
}

// UpdateEncryptedCredential sets the "encrypted_credential" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateEncryptedCredential() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateEncryptedCredential()
	})
}

// SetCredentialVersion sets the "credential_version" field.
func (u *UpstreamConnectionUpsertBulk) SetCredentialVersion(v int64) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetCredentialVersion(v)
	})
}

// AddCredentialVersion adds v to the "credential_version" field.
func (u *UpstreamConnectionUpsertBulk) AddCredentialVersion(v int64) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.AddCredentialVersion(v)
	})
}

// UpdateCredentialVersion sets the "credential_version" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateCredentialVersion() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateCredentialVersion()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamConnectionUpsertBulk) SetProxyID(v int64) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateProxyID() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamConnectionUpsertBulk) ClearProxyID() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearProxyID()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamConnectionUpsertBulk) SetStatus(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateStatus() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateStatus()
	})
}

// SetEvidenceRef sets the "evidence_ref" field.
func (u *UpstreamConnectionUpsertBulk) SetEvidenceRef(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetEvidenceRef(v)
	})
}

// UpdateEvidenceRef sets the "evidence_ref" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateEvidenceRef() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateEvidenceRef()
	})
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (u *UpstreamConnectionUpsertBulk) ClearEvidenceRef() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearEvidenceRef()
	})
}

// Exec executes the query.
func (u *UpstreamConnectionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamConnectionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamConnectionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamConnectionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
