// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountendpointprobe"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// UpstreamConnectionUpdate is the builder for updating UpstreamConnection entities.
type UpstreamConnectionUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamConnectionMutation
}

// Where appends a list predicates to the UpstreamConnectionUpdate builder.
func (_u *UpstreamConnectionUpdate) Where(ps ...predicate.UpstreamConnection) *UpstreamConnectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamConnectionUpdate) SetUpdatedAt(v time.Time) *UpstreamConnectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamConnectionUpdate) SetDeletedAt(v time.Time) *UpstreamConnectionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableDeletedAt(v *time.Time) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamConnectionUpdate) ClearDeletedAt() *UpstreamConnectionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetKind sets the "kind" field.
func (_u *UpstreamConnectionUpdate) SetKind(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableKind(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UpstreamConnectionUpdate) SetProvider(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableProvider(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *UpstreamConnectionUpdate) ClearProvider() *UpstreamConnectionUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamConnectionUpdate) SetBaseURL(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableBaseURL(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetEncryptedCredential sets the "encrypted_credential" field.
func (_u *UpstreamConnectionUpdate) SetEncryptedCredential(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetEncryptedCredential(v)
	return _u
}

// SetNillableEncryptedCredential sets the "encrypted_credential" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableEncryptedCredential(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetEncryptedCredential(*v)
	}
	return _u
}

// SetCredentialVersion sets the "credential_version" field.
func (_u *UpstreamConnectionUpdate) SetCredentialVersion(v int64) *UpstreamConnectionUpdate {
	_u.mutation.ResetCredentialVersion()
	_u.mutation.SetCredentialVersion(v)
	return _u
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableCredentialVersion(v *int64) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetCredentialVersion(*v)
	}
	return _u
}

// AddCredentialVersion adds value to the "credential_version" field.
func (_u *UpstreamConnectionUpdate) AddCredentialVersion(v int64) *UpstreamConnectionUpdate {
	_u.mutation.AddCredentialVersion(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *UpstreamConnectionUpdate) SetProxyID(v int64) *UpstreamConnectionUpdate {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableProxyID(v *int64) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *UpstreamConnectionUpdate) ClearProxyID() *UpstreamConnectionUpdate {
	_u.mutation.ClearProxyID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamConnectionUpdate) SetStatus(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableStatus(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEvidenceRef sets the "evidence_ref" field.
func (_u *UpstreamConnectionUpdate) SetEvidenceRef(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetEvidenceRef(v)
	return _u
}

// SetNillableEvidenceRef sets the "evidence_ref" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableEvidenceRef(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetEvidenceRef(*v)
	}
	return _u
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (_u *UpstreamConnectionUpdate) ClearEvidenceRef() *UpstreamConnectionUpdate {
	_u.mutation.ClearEvidenceRef()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *UpstreamConnectionUpdate) AddAccountIDs(ids ...int64) *UpstreamConnectionUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *UpstreamConnectionUpdate) AddAccounts(v ...*Account) *UpstreamConnectionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddConnectionProbeIDs adds the "connection_probes" edge to the AccountEndpointProbe entity by IDs.
func (_u *UpstreamConnectionUpdate) AddConnectionProbeIDs(ids ...int64) *UpstreamConnectionUpdate {
	_u.mutation.AddConnectionProbeIDs(ids...)
	return _u
}

// AddConnectionProbes adds the "connection_probes" edges to the AccountEndpointProbe entity.
func (_u *UpstreamConnectionUpdate) AddConnectionProbes(v ...*AccountEndpointProbe) *UpstreamConnectionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConnectionProbeIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *UpstreamConnectionUpdate) SetProxy(v *Proxy) *UpstreamConnectionUpdate {
	return _u.SetProxyID(v.ID)
}

// Mutation returns the UpstreamConnectionMutation object of the builder.
func (_u *UpstreamConnectionUpdate) Mutation() *UpstreamConnectionMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *UpstreamConnectionUpdate) ClearAccounts() *UpstreamConnectionUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *UpstreamConnectionUpdate) RemoveAccountIDs(ids ...int64) *UpstreamConnectionUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *UpstreamConnectionUpdate) RemoveAccounts(v ...*Account) *UpstreamConnectionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearConnectionProbes clears all "connection_probes" edges to the AccountEndpointProbe entity.
func (_u *UpstreamConnectionUpdate) ClearConnectionProbes() *UpstreamConnectionUpdate {
	_u.mutation.ClearConnectionProbes()
	return _u
}

// RemoveConnectionProbeIDs removes the "connection_probes" edge to AccountEndpointProbe entities by IDs.
func (_u *UpstreamConnectionUpdate) RemoveConnectionProbeIDs(ids ...int64) *UpstreamConnectionUpdate {
	_u.mutation.RemoveConnectionProbeIDs(ids...)
	return _u
}

// RemoveConnectionProbes removes "connection_probes" edges to AccountEndpointProbe entities.
func (_u *UpstreamConnectionUpdate) RemoveConnectionProbes(v ...*AccountEndpointProbe) *UpstreamConnectionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConnectionProbeIDs(ids...)
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *UpstreamConnectionUpdate) ClearProxy() *UpstreamConnectionUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamConnectionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamConnectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamConnectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamConnectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamConnectionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstreamconnection.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamconnection.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamConnectionUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := upstreamconnection.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := upstreamconnection.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamconnection.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedCredential(); ok {
		if err := upstreamconnection.EncryptedCredentialValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_credential", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.encrypted_credential": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamconnection.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamConnectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamconnection.Table, upstreamconnection.Columns, sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamconnection.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreamconnection.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(upstreamconnection.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(upstreamconnection.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(upstreamconnection.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconnection.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedCredential(); ok {
		_spec.SetField(upstreamconnection.FieldEncryptedCredential, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialVersion(); ok {
		_spec.SetField(upstreamconnection.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCredentialVersion(); ok {
		_spec.AddField(upstreamconnection.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamconnection.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvidenceRef(); ok {
		_spec.SetField(upstreamconnection.FieldEvidenceRef, field.TypeString, value)
	}
	if _u.mutation.EvidenceRefCleared() {
		_spec.ClearField(upstreamconnection.FieldEvidenceRef, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionProbesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConnectionProbesIDs(); len(nodes) > 0 && !_u.mutation.ConnectionProbesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionProbesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstreamconnection.ProxyTable,
			Columns: []string{upstreamconnection.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstreamconnection.ProxyTable,
			Columns: []string{upstreamconnection.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamConnectionUpdateOne is the builder for updating a single UpstreamConnection entity.
type UpstreamConnectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamConnectionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamConnectionUpdateOne) SetUpdatedAt(v time.Time) *UpstreamConnectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamConnectionUpdateOne) SetDeletedAt(v time.Time) *UpstreamConnectionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableDeletedAt(v *time.Time) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamConnectionUpdateOne) ClearDeletedAt() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetKind sets the "kind" field.
func (_u *UpstreamConnectionUpdateOne) SetKind(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableKind(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UpstreamConnectionUpdateOne) SetProvider(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableProvider(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *UpstreamConnectionUpdateOne) ClearProvider() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamConnectionUpdateOne) SetBaseURL(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableBaseURL(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetEncryptedCredential sets the "encrypted_credential" field.
func (_u *UpstreamConnectionUpdateOne) SetEncryptedCredential(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetEncryptedCredential(v)
	return _u
}

// SetNillableEncryptedCredential sets the "encrypted_credential" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableEncryptedCredential(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetEncryptedCredential(*v)
	}
	return _u
}

// SetCredentialVersion sets the "credential_version" field.
func (_u *UpstreamConnectionUpdateOne) SetCredentialVersion(v int64) *UpstreamConnectionUpdateOne {
	_u.mutation.ResetCredentialVersion()
	_u.mutation.SetCredentialVersion(v)
	return _u
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableCredentialVersion(v *int64) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetCredentialVersion(*v)
	}
	return _u
}

// AddCredentialVersion adds value to the "credential_version" field.
func (_u *UpstreamConnectionUpdateOne) AddCredentialVersion(v int64) *UpstreamConnectionUpdateOne {
	_u.mutation.AddCredentialVersion(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *UpstreamConnectionUpdateOne) SetProxyID(v int64) *UpstreamConnectionUpdateOne {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableProxyID(v *int64) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *UpstreamConnectionUpdateOne) ClearProxyID() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearProxyID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamConnectionUpdateOne) SetStatus(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableStatus(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEvidenceRef sets the "evidence_ref" field.
func (_u *UpstreamConnectionUpdateOne) SetEvidenceRef(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetEvidenceRef(v)
	return _u
}

// SetNillableEvidenceRef sets the "evidence_ref" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableEvidenceRef(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetEvidenceRef(*v)
	}
	return _u
}

// ClearEvidenceRef clears the value of the "evidence_ref" field.
func (_u *UpstreamConnectionUpdateOne) ClearEvidenceRef() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearEvidenceRef()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *UpstreamConnectionUpdateOne) AddAccountIDs(ids ...int64) *UpstreamConnectionUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *UpstreamConnectionUpdateOne) AddAccounts(v ...*Account) *UpstreamConnectionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddConnectionProbeIDs adds the "connection_probes" edge to the AccountEndpointProbe entity by IDs.
func (_u *UpstreamConnectionUpdateOne) AddConnectionProbeIDs(ids ...int64) *UpstreamConnectionUpdateOne {
	_u.mutation.AddConnectionProbeIDs(ids...)
	return _u
}

// AddConnectionProbes adds the "connection_probes" edges to the AccountEndpointProbe entity.
func (_u *UpstreamConnectionUpdateOne) AddConnectionProbes(v ...*AccountEndpointProbe) *UpstreamConnectionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConnectionProbeIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *UpstreamConnectionUpdateOne) SetProxy(v *Proxy) *UpstreamConnectionUpdateOne {
	return _u.SetProxyID(v.ID)
}

// Mutation returns the UpstreamConnectionMutation object of the builder.
func (_u *UpstreamConnectionUpdateOne) Mutation() *UpstreamConnectionMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *UpstreamConnectionUpdateOne) ClearAccounts() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *UpstreamConnectionUpdateOne) RemoveAccountIDs(ids ...int64) *UpstreamConnectionUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *UpstreamConnectionUpdateOne) RemoveAccounts(v ...*Account) *UpstreamConnectionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearConnectionProbes clears all "connection_probes" edges to the AccountEndpointProbe entity.
func (_u *UpstreamConnectionUpdateOne) ClearConnectionProbes() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearConnectionProbes()
	return _u
}

// RemoveConnectionProbeIDs removes the "connection_probes" edge to AccountEndpointProbe entities by IDs.
func (_u *UpstreamConnectionUpdateOne) RemoveConnectionProbeIDs(ids ...int64) *UpstreamConnectionUpdateOne {
	_u.mutation.RemoveConnectionProbeIDs(ids...)
	return _u
}

// RemoveConnectionProbes removes "connection_probes" edges to AccountEndpointProbe entities.
func (_u *UpstreamConnectionUpdateOne) RemoveConnectionProbes(v ...*AccountEndpointProbe) *UpstreamConnectionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConnectionProbeIDs(ids...)
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *UpstreamConnectionUpdateOne) ClearProxy() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// Where appends a list predicates to the UpstreamConnectionUpdate builder.
func (_u *UpstreamConnectionUpdateOne) Where(ps ...predicate.UpstreamConnection) *UpstreamConnectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamConnectionUpdateOne) Select(field string, fields ...string) *UpstreamConnectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamConnection entity.
func (_u *UpstreamConnectionUpdateOne) Save(ctx context.Context) (*UpstreamConnection, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamConnectionUpdateOne) SaveX(ctx context.Context) *UpstreamConnection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamConnectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamConnectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamConnectionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstreamconnection.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamconnection.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamConnectionUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := upstreamconnection.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := upstreamconnection.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamconnection.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedCredential(); ok {
		if err := upstreamconnection.EncryptedCredentialValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_credential", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.encrypted_credential": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamconnection.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamConnectionUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamConnection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamconnection.Table, upstreamconnection.Columns, sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamConnection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamconnection.FieldID)
		for _, f := range fields {
			if !upstreamconnection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamconnection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamconnection.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreamconnection.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(upstreamconnection.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(upstreamconnection.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(upstreamconnection.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconnection.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedCredential(); ok {
		_spec.SetField(upstreamconnection.FieldEncryptedCredential, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialVersion(); ok {
		_spec.SetField(upstreamconnection.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCredentialVersion(); ok {
		_spec.AddField(upstreamconnection.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamconnection.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvidenceRef(); ok {
		_spec.SetField(upstreamconnection.FieldEvidenceRef, field.TypeString, value)
	}
	if _u.mutation.EvidenceRefCleared() {
		_spec.ClearField(upstreamconnection.FieldEvidenceRef, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   upstreamconnection.AccountsTable,
			Columns: []string{upstreamconnection.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionProbesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConnectionProbesIDs(); len(nodes) > 0 && !_u.mutation.ConnectionProbesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionProbesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.ConnectionProbesTable,
			Columns: []string{upstreamconnection.ConnectionProbesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountendpointprobe.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstreamconnection.ProxyTable,
			Columns: []string{upstreamconnection.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstreamconnection.ProxyTable,
			Columns: []string{upstreamconnection.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamConnection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
