// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// UpstreamConnection is the model entity for the UpstreamConnection schema.
type UpstreamConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// first_party or aggregator
	Kind string `json:"kind,omitempty"`
	// governed provider or null for aggregator
	Provider *string `json:"provider,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// EncryptedCredential holds the value of the "encrypted_credential" field.
	EncryptedCredential string `json:"encrypted_credential,omitempty"`
	// optimistic version, >0
	CredentialVersion int64 `json:"credential_version,omitempty"`
	// optional proxy id
	ProxyID *int64 `json:"proxy_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// EvidenceRef holds the value of the "evidence_ref" field.
	EvidenceRef *string `json:"evidence_ref,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamConnectionQuery when eager-loading is set.
	Edges        UpstreamConnectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamConnectionEdges holds the relations/edges for other nodes in the graph.
type UpstreamConnectionEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// ConnectionProbes holds the value of the connection_probes edge.
	ConnectionProbes []*AccountEndpointProbe `json:"connection_probes,omitempty"`
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamConnectionEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// ConnectionProbesOrErr returns the ConnectionProbes value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamConnectionEdges) ConnectionProbesOrErr() ([]*AccountEndpointProbe, error) {
	if e.loadedTypes[1] {
		return e.ConnectionProbes, nil
	}
	return nil, &NotLoadedError{edge: "connection_probes"}
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamConnectionEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamconnection.FieldID, upstreamconnection.FieldCredentialVersion, upstreamconnection.FieldProxyID:
			values[i] = new(sql.NullInt64)
		case upstreamconnection.FieldKind, upstreamconnection.FieldProvider, upstreamconnection.FieldBaseURL, upstreamconnection.FieldEncryptedCredential, upstreamconnection.FieldStatus, upstreamconnection.FieldEvidenceRef:
			values[i] = new(sql.NullString)
		case upstreamconnection.FieldCreatedAt, upstreamconnection.FieldUpdatedAt, upstreamconnection.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamConnection fields.
func (_m *UpstreamConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamconnection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamconnection.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case upstreamconnection.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case upstreamconnection.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = new(string)
				*_m.Provider = value.String
			}
		case upstreamconnection.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstreamconnection.FieldEncryptedCredential:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_credential", values[i])
			} else if value.Valid {
				_m.EncryptedCredential = value.String
			}
		case upstreamconnection.FieldCredentialVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credential_version", values[i])
			} else if value.Valid {
				_m.CredentialVersion = value.Int64
			}
		case upstreamconnection.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = new(int64)
				*_m.ProxyID = value.Int64
			}
		case upstreamconnection.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case upstreamconnection.FieldEvidenceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field evidence_ref", values[i])
			} else if value.Valid {
				_m.EvidenceRef = new(string)
				*_m.EvidenceRef = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamConnection.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QueryAccounts() *AccountQuery {
	return NewUpstreamConnectionClient(_m.config).QueryAccounts(_m)
}

// QueryConnectionProbes queries the "connection_probes" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QueryConnectionProbes() *AccountEndpointProbeQuery {
	return NewUpstreamConnectionClient(_m.config).QueryConnectionProbes(_m)
}

// QueryProxy queries the "proxy" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QueryProxy() *ProxyQuery {
	return NewUpstreamConnectionClient(_m.config).QueryProxy(_m)
}

// Update returns a builder for updating this UpstreamConnection.
// Note that you need to call UpstreamConnection.Unwrap() before calling this method if this UpstreamConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamConnection) Update() *UpstreamConnectionUpdateOne {
	return NewUpstreamConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamConnection) Unwrap() *UpstreamConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamConnection) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	if v := _m.Provider; v != nil {
		builder.WriteString("provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("encrypted_credential=")
	builder.WriteString(_m.EncryptedCredential)
	builder.WriteString(", ")
	builder.WriteString("credential_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialVersion))
	builder.WriteString(", ")
	if v := _m.ProxyID; v != nil {
		builder.WriteString("proxy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.EvidenceRef; v != nil {
		builder.WriteString("evidence_ref=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamConnections is a parsable slice of UpstreamConnection.
type UpstreamConnections []*UpstreamConnection
