// Code generated by ent, DO NOT EDIT.

package accountendpointprobe

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accountendpointprobe type in the database.
	Label = "account_endpoint_probe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldNormalizedEndpointPath holds the string denoting the normalized_endpoint_path field in the database.
	FieldNormalizedEndpointPath = "normalized_endpoint_path"
	// FieldCredentialVersion holds the string denoting the credential_version field in the database.
	FieldCredentialVersion = "credential_version"
	// FieldConfigVersion holds the string denoting the config_version field in the database.
	FieldConfigVersion = "config_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProbedAt holds the string denoting the probed_at field in the database.
	FieldProbedAt = "probed_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldEvidenceRef holds the string denoting the evidence_ref field in the database.
	FieldEvidenceRef = "evidence_ref"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldResponseSummary holds the string denoting the response_summary field in the database.
	FieldResponseSummary = "response_summary"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeConnection holds the string denoting the connection edge name in mutations.
	EdgeConnection = "connection"
	// Table holds the table name of the accountendpointprobe in the database.
	Table = "account_endpoint_probes"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "account_endpoint_probes"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// ConnectionTable is the table that holds the connection relation/edge.
	ConnectionTable = "account_endpoint_probes"
	// ConnectionInverseTable is the table name for the UpstreamConnection entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamconnection" package.
	ConnectionInverseTable = "upstream_connections"
	// ConnectionColumn is the table column denoting the connection relation/edge.
	ConnectionColumn = "connection_id"
)

// Columns holds all SQL columns for accountendpointprobe fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldConnectionID,
	FieldProvider,
	FieldProtocol,
	FieldNormalizedEndpointPath,
	FieldCredentialVersion,
	FieldConfigVersion,
	FieldStatus,
	FieldProbedAt,
	FieldExpiresAt,
	FieldEvidenceRef,
	FieldRequestFingerprint,
	FieldResponseSummary,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// NormalizedEndpointPathValidator is a validator for the "normalized_endpoint_path" field. It is called by the builders before save.
	NormalizedEndpointPathValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultResponseSummary holds the default value on creation for the "response_summary" field.
	DefaultResponseSummary func() map[string]interface{}
)

// OrderOption defines the ordering options for the AccountEndpointProbe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByNormalizedEndpointPath orders the results by the normalized_endpoint_path field.
func ByNormalizedEndpointPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedEndpointPath, opts...).ToFunc()
}

// ByCredentialVersion orders the results by the credential_version field.
func ByCredentialVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialVersion, opts...).ToFunc()
}

// ByConfigVersion orders the results by the config_version field.
func ByConfigVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProbedAt orders the results by the probed_at field.
func ByProbedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByEvidenceRef orders the results by the evidence_ref field.
func ByEvidenceRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvidenceRef, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByConnectionField orders the results by connection field.
func ByConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectionStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
	)
}
