// Code generated by ent, DO NOT EDIT.

package accountendpointprobe

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldAccountID, v))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldConnectionID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldProvider, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldProtocol, v))
}

// NormalizedEndpointPath applies equality check predicate on the "normalized_endpoint_path" field. It's identical to NormalizedEndpointPathEQ.
func NormalizedEndpointPath(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldNormalizedEndpointPath, v))
}

// CredentialVersion applies equality check predicate on the "credential_version" field. It's identical to CredentialVersionEQ.
func CredentialVersion(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldCredentialVersion, v))
}

// ConfigVersion applies equality check predicate on the "config_version" field. It's identical to ConfigVersionEQ.
func ConfigVersion(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldConfigVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldStatus, v))
}

// ProbedAt applies equality check predicate on the "probed_at" field. It's identical to ProbedAtEQ.
func ProbedAt(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldProbedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldExpiresAt, v))
}

// EvidenceRef applies equality check predicate on the "evidence_ref" field. It's identical to EvidenceRefEQ.
func EvidenceRef(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldEvidenceRef, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldRequestFingerprint, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldAccountID, vs...))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContainsFold(FieldProvider, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContainsFold(FieldProtocol, v))
}

// NormalizedEndpointPathEQ applies the EQ predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathNEQ applies the NEQ predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathNEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathIn applies the In predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldNormalizedEndpointPath, vs...))
}

// NormalizedEndpointPathNotIn applies the NotIn predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathNotIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldNormalizedEndpointPath, vs...))
}

// NormalizedEndpointPathGT applies the GT predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathGT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathGTE applies the GTE predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathGTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathLT applies the LT predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathLT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathLTE applies the LTE predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathLTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathContains applies the Contains predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathContains(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContains(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathHasPrefix applies the HasPrefix predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathHasPrefix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasPrefix(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathHasSuffix applies the HasSuffix predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathHasSuffix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasSuffix(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathEqualFold applies the EqualFold predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathEqualFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEqualFold(FieldNormalizedEndpointPath, v))
}

// NormalizedEndpointPathContainsFold applies the ContainsFold predicate on the "normalized_endpoint_path" field.
func NormalizedEndpointPathContainsFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContainsFold(FieldNormalizedEndpointPath, v))
}

// CredentialVersionEQ applies the EQ predicate on the "credential_version" field.
func CredentialVersionEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldCredentialVersion, v))
}

// CredentialVersionNEQ applies the NEQ predicate on the "credential_version" field.
func CredentialVersionNEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldCredentialVersion, v))
}

// CredentialVersionIn applies the In predicate on the "credential_version" field.
func CredentialVersionIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldCredentialVersion, vs...))
}

// CredentialVersionNotIn applies the NotIn predicate on the "credential_version" field.
func CredentialVersionNotIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldCredentialVersion, vs...))
}

// CredentialVersionGT applies the GT predicate on the "credential_version" field.
func CredentialVersionGT(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldCredentialVersion, v))
}

// CredentialVersionGTE applies the GTE predicate on the "credential_version" field.
func CredentialVersionGTE(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldCredentialVersion, v))
}

// CredentialVersionLT applies the LT predicate on the "credential_version" field.
func CredentialVersionLT(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldCredentialVersion, v))
}

// CredentialVersionLTE applies the LTE predicate on the "credential_version" field.
func CredentialVersionLTE(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldCredentialVersion, v))
}

// ConfigVersionEQ applies the EQ predicate on the "config_version" field.
func ConfigVersionEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldConfigVersion, v))
}

// ConfigVersionNEQ applies the NEQ predicate on the "config_version" field.
func ConfigVersionNEQ(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldConfigVersion, v))
}

// ConfigVersionIn applies the In predicate on the "config_version" field.
func ConfigVersionIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldConfigVersion, vs...))
}

// ConfigVersionNotIn applies the NotIn predicate on the "config_version" field.
func ConfigVersionNotIn(vs ...int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldConfigVersion, vs...))
}

// ConfigVersionGT applies the GT predicate on the "config_version" field.
func ConfigVersionGT(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldConfigVersion, v))
}

// ConfigVersionGTE applies the GTE predicate on the "config_version" field.
func ConfigVersionGTE(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldConfigVersion, v))
}

// ConfigVersionLT applies the LT predicate on the "config_version" field.
func ConfigVersionLT(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldConfigVersion, v))
}

// ConfigVersionLTE applies the LTE predicate on the "config_version" field.
func ConfigVersionLTE(v int64) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldConfigVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContainsFold(FieldStatus, v))
}

// ProbedAtEQ applies the EQ predicate on the "probed_at" field.
func ProbedAtEQ(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldProbedAt, v))
}

// ProbedAtNEQ applies the NEQ predicate on the "probed_at" field.
func ProbedAtNEQ(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldProbedAt, v))
}

// ProbedAtIn applies the In predicate on the "probed_at" field.
func ProbedAtIn(vs ...time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldProbedAt, vs...))
}

// ProbedAtNotIn applies the NotIn predicate on the "probed_at" field.
func ProbedAtNotIn(vs ...time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldProbedAt, vs...))
}

// ProbedAtGT applies the GT predicate on the "probed_at" field.
func ProbedAtGT(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldProbedAt, v))
}

// ProbedAtGTE applies the GTE predicate on the "probed_at" field.
func ProbedAtGTE(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldProbedAt, v))
}

// ProbedAtLT applies the LT predicate on the "probed_at" field.
func ProbedAtLT(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldProbedAt, v))
}

// ProbedAtLTE applies the LTE predicate on the "probed_at" field.
func ProbedAtLTE(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldProbedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldExpiresAt, v))
}

// EvidenceRefEQ applies the EQ predicate on the "evidence_ref" field.
func EvidenceRefEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldEvidenceRef, v))
}

// EvidenceRefNEQ applies the NEQ predicate on the "evidence_ref" field.
func EvidenceRefNEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldEvidenceRef, v))
}

// EvidenceRefIn applies the In predicate on the "evidence_ref" field.
func EvidenceRefIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldEvidenceRef, vs...))
}

// EvidenceRefNotIn applies the NotIn predicate on the "evidence_ref" field.
func EvidenceRefNotIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldEvidenceRef, vs...))
}

// EvidenceRefGT applies the GT predicate on the "evidence_ref" field.
func EvidenceRefGT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldEvidenceRef, v))
}

// EvidenceRefGTE applies the GTE predicate on the "evidence_ref" field.
func EvidenceRefGTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldEvidenceRef, v))
}

// EvidenceRefLT applies the LT predicate on the "evidence_ref" field.
func EvidenceRefLT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldEvidenceRef, v))
}

// EvidenceRefLTE applies the LTE predicate on the "evidence_ref" field.
func EvidenceRefLTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldEvidenceRef, v))
}

// EvidenceRefContains applies the Contains predicate on the "evidence_ref" field.
func EvidenceRefContains(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContains(FieldEvidenceRef, v))
}

// EvidenceRefHasPrefix applies the HasPrefix predicate on the "evidence_ref" field.
func EvidenceRefHasPrefix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasPrefix(FieldEvidenceRef, v))
}

// EvidenceRefHasSuffix applies the HasSuffix predicate on the "evidence_ref" field.
func EvidenceRefHasSuffix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasSuffix(FieldEvidenceRef, v))
}

// EvidenceRefIsNil applies the IsNil predicate on the "evidence_ref" field.
func EvidenceRefIsNil() predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIsNull(FieldEvidenceRef))
}

// EvidenceRefNotNil applies the NotNil predicate on the "evidence_ref" field.
func EvidenceRefNotNil() predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotNull(FieldEvidenceRef))
}

// EvidenceRefEqualFold applies the EqualFold predicate on the "evidence_ref" field.
func EvidenceRefEqualFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEqualFold(FieldEvidenceRef, v))
}

// EvidenceRefContainsFold applies the ContainsFold predicate on the "evidence_ref" field.
func EvidenceRefContainsFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContainsFold(FieldEvidenceRef, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintIsNil applies the IsNil predicate on the "request_fingerprint" field.
func RequestFingerprintIsNil() predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldIsNull(FieldRequestFingerprint))
}

// RequestFingerprintNotNil applies the NotNil predicate on the "request_fingerprint" field.
func RequestFingerprintNotNil() predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldNotNull(FieldRequestFingerprint))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.UpstreamConnection) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountEndpointProbe) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountEndpointProbe) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountEndpointProbe) predicate.AccountEndpointProbe {
	return predicate.AccountEndpointProbe(sql.NotPredicates(p))
}
